### ISSUE TITLE
Update to use `inputs` when inspec 4.6.x drops 

### ISSUE THREAD

**Issue by aaronlippold** [mitre/canonical-ubuntu-16.04-lts-stig-baseline#10]

**Comment by kkola** [comment]
I'm trying to leverage the new input plugin in InSpec 4.6.3 per the documentation available here: [https://www.inspec.io/docs/reference/inputs/](url).

I tried using the first simple example structure from the documentation for input specification in inspec.yml, including a 'value' key for the input. Then, in my control code I access the input using:
`amplifier_max_volume = input('amplifier_max_volume')`

and execute the control using:
`inspec exec <CONTROL_LOCATION> -t ssh://vagrant@127.0.0.1:2222 -i <KEY_PATH> --sudo --input-file inspec.yml`

Doing so, I get this error:
`can't convert Inspec::Input::NO_VALUE_SET to Array (Inspec::Input::NO_VALUE_SET#to_ary gives Inspec::Input::NO_VALUE_SET)`

But `inspec exec` works if I modify the input structure to be similar to the old attributes structure like so:
`amplifier_max_volume: 100`

Is this a bug in InSpec or something wrong with how I'm trying to go about writing this?

**Comment by kkola** [comment]
migrated profile to use inputs instead of attributes
