### ISSUE TITLE
rename the repo to follow standard naming convention

### ISSUE THREAD

**Issue by aaronlippold** [mitre/canonical-ubuntu-16.04-lts-stig-baseline#12]

**Comment by ejaronne** [comment]
as I mentioned in https://github.com/mitre/stig-canonical-ubuntu-16.04-lts-baseline/issues/2

Our convention is vendor-product-version-edition[-stig|cis]-baseline

So the name should be:
canonical-ubuntu-16.04-lts-stig-baseline

**Comment by kkola** [comment]
renamed repository to canonical-ubuntu-16.04-lts-stig-baseline
