### ISSUE TITLE
Inspec syntax check 

### ISSUE THREAD

**Issue by HackerShark** [mitre/canonical-ubuntu-16.04-lts-stig-baseline#17]
Running inspec check on the profile came up with these results:

![inspec_check](https://user-images.githubusercontent.com/16725004/62800831-62709080-bab2-11e9-8a74-08fa2cccbba2.png)

**Comment by amolshah** [comment]
The control implementation is correct. This is caused by an issue with Inspec check..https://github.com/inspec/inspec/issues/3550
