### ISSUE TITLE
V-75437 - Change impact

### ISSUE THREAD

**Issue by HackerShark** [mitre/canonical-ubuntu-16.04-lts-stig-baseline#19]
For control [V-75437](../blob/development/controls/V-75437.rb) the logic goes like this:

```
gnome_installed = (package('ubuntu-gnome-desktop').installed? || package('ubuntu-desktop').installed?)

  if gnome_installed
    lock_enabled = command('gsettings get org.gnome.desktop.screensaver lock-enabled')
    describe lock_enabled do
      its('stdout') { should cmp 'true' }
    end
  else
    describe "Not Applicable as GNOME dekstop environment is installed" do
      subject { gnome_installed }
      it { should be false }
    end
  end
end
```

If you run into a Not Applicable scenario as you do in your else block, we want the impact to be 0 as this check is not applicable to the environment. So make sure to add a line `impact 0` within that else block to update the impact score.

**Comment by HackerShark** [comment]
Control V-75495 also has the same problem

**Comment by HackerShark** [comment]
V-75891 same issue

**Comment by HackerShark** [comment]
V-75893 same issue

**Comment by HackerShark** [comment]
V-75899 same issue

**Comment by HackerShark** [comment]
V-80957 same issue

**Comment by amolshah** [comment]
This change was completed for control V-75437
