### ISSUE TITLE
V-75511 - Looping Directory

### ISSUE THREAD

**Issue by HackerShark** [mitre/canonical-ubuntu-16.04-lts-stig-baseline#20]
When looping a directory it's best to consolidate the find command as much as possible so as not to have a long running control. Preferable to add the `-maxdepth 0` with the max directory depth you require as well as  `-xdev` options.

**Comment by HackerShark** [comment]
V-75513 same issue

**Comment by HackerShark** [comment]
V-75555 same issue

**Comment by HackerShark** [comment]
V-75557 same issue

**Comment by HackerShark** [comment]
V-75583 same issue

**Comment by HackerShark** [comment]
V-75605 same issue

**Comment by HackerShark** [comment]
V-75607 same issue

**Comment by HackerShark** [comment]
V-75609 same issue

**Comment by HackerShark** [comment]
V-75611 same issue

**Comment by HackerShark** [comment]
V-75613 same issue

**Comment by HackerShark** [comment]
V-75615 same issue

**Comment by HackerShark** [comment]
V-75583 same issue

**Comment by HackerShark** [comment]
V-75811 same issue

**Comment by HackerShark** [comment]
V-75843 same issue

**Comment by HackerShark** [comment]
V-75845 same issue

**Comment by HackerShark** [comment]
V-78007 same issue

**Comment by ejaronne** [comment]
I did some "what did the RHEL7 STIG say" comparisons, and my own impressions and recommend:


Number | -xdev | -maxdepth | Use a disable_slow_control attribute | Comment
-- | -- | -- | -- | --
75511 | Yes | NO | No | Similar to https://github.com/simp/inspec-profile-disa_stig-el7/blob/master/controls/V-72047.rb
75513 | Yes | NO | No | Similar to https://github.com/simp/inspec-profile-disa_stig-el7/blob/master/controls/V-72047.rb
75555 | No | No | Maybe | Let’s see how slow it is in our tests
75557 | No | No | No | https://github.com/simp/inspec-profile-disa_stig-el7/blob/master/controls/V-72009.rb
75583 | Yes | NO | No | Similar to https://github.com/simp/inspec-profile-disa_stig-el7/blob/master/controls/V-72047.rb
75605 | No | No | Maybe | Let’s see how slow it is in our tests
75607 | No | No | Maybe | Let’s see how slow it is in our tests
75609 | No | No | Maybe | Let’s see how slow it is in our tests
75611 | No | No | Maybe | Let’s see how slow it is in our tests
75613 | No | No | Maybe | Let’s see how slow it is in our tests
75615 | No | No | Maybe | Let’s see how slow it is in our tests
75811 | Yes | NO | No | Similar to https://github.com/simp/inspec-profile-disa_stig-el7/blob/master/controls/V-72047.rb
78007 | No | No | No |  
75843 | No? | No | No | Why is xdev currently bothered to be set? This checks   the /etc/ssh directory. Do we really think something under this would be   mounted to another filesystem?
75845 | No? | No | No | Why is xdev currently bothered to be set? This checks   the /etc/ssh directory. Do we really think something under this would be   mounted to another filesystem?
