### ISSUE TITLE
Remove comments from the following controls

### ISSUE THREAD

**Issue by HackerShark** [mitre/canonical-ubuntu-16.04-lts-stig-baseline#21]
Control list with comments that need to be removed:

- [ ] V-75445
- [x] V-75517
- [x] V-75523
- [x] V-75527
- [x] V-75535
- [x] V-75555
- [x] V-75571
- [x] V-75573
- [x] V-75587
- [x] V-75661
- [x] V-75663
- [x] V-75665
- [x] V-75667
- [x] V-75687
- [x] V-75691
- [x] V-75693
- [x] V-75695
- [x] V-75697
- [x] V-75699
- [x] V-75707
- [x] V-75709
- [x] V-75711
- [x] V-75713
- [x] V-75715
- [x] V-75755
- [x] V-75757
- [x] V-75759
- [x] V-75761
- [x] V-75765
- [x] V-75767
- [x] V-75769
- [x] V-75771
- [x] V-75773
- [x] V-75775
- [x] V-75777
- [x] V-75779
- [x] V-75781
- [x] V-75783
- [x] V-75785
- [x] V-75787
- [x] V-75789
- [x] V-75825
- [x] V-78007
- [x] V-80969

**Comment by aaronlippold** [comment]
Fixed by 68ad0db
