### ISSUE TITLE
auditd architecture

### ISSUE THREAD

**Issue by HackerShark** [mitre/canonical-ubuntu-16.04-lts-stig-baseline#23]
Controls are written expecting a 64bit architecture. Consider having an 'input' or else statements in the controls to test if they use a 32bit architecture instead.

Controls affected:

1. - [x] V-75605
2. - [x] V-75607
3. - [x] V-75609
4. - [x] V-75689
5. - [x] V-75717
6. - [x] V-75719
7. - [x] V-75721
8. - [x] V-75723
9. - [x] V-75725
10. - [x] V-75727
11. - [x] V-75729
12. - [x] V-75731
13. - [x] V-75733
14. - [x] V-75735
15. - [x] V-75737
16. - [x] V-75739
17. - [x] V-75741
18. - [x] V-75743
19. - [x] V-75745
20. - [x] V-75747
21. - [x] V-75749
22. - [x] V-75751
23. - [x] V-75753
24. - [x] V-75791
25. - [x] V-75793
26. - [x] V-75795

**Comment by aaronlippold** [comment]
64 bit needs both 32 bit and 64 bit tests.  A simple if else like we did on
rhel7 should do

**Comment by kkola** [comment]
Fixed the 26 controls listed in the issue

**Comment by aaronlippold** [comment]
Fixed by #15
