### ISSUE TITLE
update .kitchen.*.yml files to also include the tarvis build id or some identifier

### ISSUE THREAD

**Issue by aaronlippold** [mitre/canonical-ubuntu-16.04-lts-stig-baseline#6]
This will help ensure that JSONs are clearly linked to the PRs and builds they come from

**Comment by kkola** [comment]
commit [https://github.com/mitre/canonical-ubuntu-16.04-lts-stig-baseline/commit/4bbf04feb47b6d86b62a973190f25d884eed34b7](url) resolves this
