### ISSUE TITLE
Review all - 'more permissive than' to use the new matcher when possible

### ISSUE THREAD

**Issue by aaronlippold** [mitre/canonical-ubuntu-16.04-lts-stig-baseline#9]
We are borrowing form the RHEL stig on this which uses an effective but possibly outdated method of testing. We will allow this for now but in the end I would like this to be reviewed and enhanced on our Peer Review.

**Comment by aaronlippold** [comment]
- [ ] 75569
- [ ] others?

**Comment by kkola** [comment]
Migrated relevant controls in profile to use more_permissive_than matcher
